export const cx     = (re, im = 0) => ({ re, im });
export const cAdd   = (a, b) => ({ re: a.re + b.re, im: a.im + b.im });
export const cSub   = (a, b) => ({ re: a.re - b.re, im: a.im - b.im });
export const cMul   = (a, b) => ({ re: a.re*b.re - a.im*b.im, im: a.re*b.im + a.im*b.re });
export const cDiv   = (a, b) => { const d = b.re*b.re + b.im*b.im; return { re: (a.re*b.re + a.im*b.im)/d, im: (a.im*b.re - a.re*b.im)/d }; };
export const cInv   = (a)    => { const d = a.re*a.re + a.im*a.im; return { re: a.re/d, im: -a.im/d }; };
export const cAbs   = (a)    => Math.hypot(a.re, a.im);
export const cArg   = (a)    => Math.atan2(a.im, a.re);
export const cScale = (a, k) => ({ re: a.re*k, im: a.im*k });
export const cPar   = (...zs) => cInv(zs.reduce((s, z) => cAdd(s, cInv(z)), cx(0, 0)));
